# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Occlusion_pose.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14Occlusion_pose.proto\"\x1d\n\x0c\x46loat1DArray\x12\r\n\x05\x65lems\x18\x01 \x03(\x02\",\n\x0c\x46loat2DArray\x12\x1c\n\x05lines\x18\x01 \x03(\x0b\x32\r.Float1DArray\"/\n\x0c\x46loat3DArray\x12\x1f\n\x08matrices\x18\x01 \x03(\x0b\x32\r.Float2DArray\"\x15\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1c\n\x0bPoseRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\":\n\x0cPoseResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x1b\n\x04pose\x18\x02 \x01(\x0b\x32\r.Float2DArray21\n\rOcclusionPose\x12 \n\x07Process\x12\x06.Image\x1a\r.PoseResponseb\x06proto3')



_FLOAT1DARRAY = DESCRIPTOR.message_types_by_name['Float1DArray']
_FLOAT2DARRAY = DESCRIPTOR.message_types_by_name['Float2DArray']
_FLOAT3DARRAY = DESCRIPTOR.message_types_by_name['Float3DArray']
_IMAGE = DESCRIPTOR.message_types_by_name['Image']
_POSEREQUEST = DESCRIPTOR.message_types_by_name['PoseRequest']
_POSERESPONSE = DESCRIPTOR.message_types_by_name['PoseResponse']
Float1DArray = _reflection.GeneratedProtocolMessageType('Float1DArray', (_message.Message,), {
  'DESCRIPTOR' : _FLOAT1DARRAY,
  '__module__' : 'Occlusion_pose_pb2'
  # @@protoc_insertion_point(class_scope:Float1DArray)
  })
_sym_db.RegisterMessage(Float1DArray)

Float2DArray = _reflection.GeneratedProtocolMessageType('Float2DArray', (_message.Message,), {
  'DESCRIPTOR' : _FLOAT2DARRAY,
  '__module__' : 'Occlusion_pose_pb2'
  # @@protoc_insertion_point(class_scope:Float2DArray)
  })
_sym_db.RegisterMessage(Float2DArray)

Float3DArray = _reflection.GeneratedProtocolMessageType('Float3DArray', (_message.Message,), {
  'DESCRIPTOR' : _FLOAT3DARRAY,
  '__module__' : 'Occlusion_pose_pb2'
  # @@protoc_insertion_point(class_scope:Float3DArray)
  })
_sym_db.RegisterMessage(Float3DArray)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'Occlusion_pose_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  })
_sym_db.RegisterMessage(Image)

PoseRequest = _reflection.GeneratedProtocolMessageType('PoseRequest', (_message.Message,), {
  'DESCRIPTOR' : _POSEREQUEST,
  '__module__' : 'Occlusion_pose_pb2'
  # @@protoc_insertion_point(class_scope:PoseRequest)
  })
_sym_db.RegisterMessage(PoseRequest)

PoseResponse = _reflection.GeneratedProtocolMessageType('PoseResponse', (_message.Message,), {
  'DESCRIPTOR' : _POSERESPONSE,
  '__module__' : 'Occlusion_pose_pb2'
  # @@protoc_insertion_point(class_scope:PoseResponse)
  })
_sym_db.RegisterMessage(PoseResponse)

_OCCLUSIONPOSE = DESCRIPTOR.services_by_name['OcclusionPose']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLOAT1DARRAY._serialized_start=24
  _FLOAT1DARRAY._serialized_end=53
  _FLOAT2DARRAY._serialized_start=55
  _FLOAT2DARRAY._serialized_end=99
  _FLOAT3DARRAY._serialized_start=101
  _FLOAT3DARRAY._serialized_end=148
  _IMAGE._serialized_start=150
  _IMAGE._serialized_end=171
  _POSEREQUEST._serialized_start=173
  _POSEREQUEST._serialized_end=201
  _POSERESPONSE._serialized_start=203
  _POSERESPONSE._serialized_end=261
  _OCCLUSIONPOSE._serialized_start=263
  _OCCLUSIONPOSE._serialized_end=312
# @@protoc_insertion_point(module_scope)
