stages:
  - name: "Source"
    host: image-source
    port: 8061
    method: GetStream
  - name: "Model"
    host: headpose-model
    port: 8061
  - name: "Visualization"
    host: headpose-visualization
    port: 8061
links:
  - source:
      stage: "Source"
    target:
      stage: "Model"
  - source:
      stage: "Model"
    target:
      stage: "Visualization"