version: '3'
services:
  image-source:
    image: sipgisr/image-source:latest
    volumes:
    - type: bind
      source: ./images/
      target: /workspace/images/
  headpose-model:
    image: occlusionpose
  headpose-visualization:
    image: sipgisr/image-visualization
    ports:
    - 8062:8062
  orchestrator-node:
    image: sipgisr/grpc-orchestrator:latest
    volumes: 
    - type: bind
      source: ./config.yml
      target: /app/config.yml
    environment:
      CONFIG_FILE: "config.yml"
    command: bash -c "/usr/bin/wait-for-all.sh config/urls.txt && java -cp '*' pipeline.orchestrator.App"